version: '3.8'

services:
  arangodb_mcp_arango_server:
    image: arangodb:latest
    environment:
      - ARANGO_ROOT_PASSWORD=rootpassword
    ports:
      - "8530:8529"
    volumes:
      - arangodb_data:/var/lib/arangodb3
      - arangodb_apps:/var/lib/arangodb3-apps
    restart: unless-stopped

volumes:
  arangodb_data:
  arangodb_apps: 